// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpc2IkMYlCqkWol9ZQSLY8U7o04GjuJgA',
    appId: '1:316915061318:web:36fe4718e40758cbacf047',
    messagingSenderId: '316915061318',
    projectId: 'flutter-chat-app-a36e9',
    authDomain: 'flutter-chat-app-a36e9.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a36e9.firebasestorage.app',
    measurementId: 'G-R9CC4G514F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvlcTkpMS_V-HjwJDDz0x0lBQgkEli5VU',
    appId: '1:316915061318:android:f8ece126db6c73c2acf047',
    messagingSenderId: '316915061318',
    projectId: 'flutter-chat-app-a36e9',
    storageBucket: 'flutter-chat-app-a36e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4bOz2HaPCYKDM6gALJM7NmPZQpZVfXeE',
    appId: '1:316915061318:ios:508ca53f1799df79acf047',
    messagingSenderId: '316915061318',
    projectId: 'flutter-chat-app-a36e9',
    storageBucket: 'flutter-chat-app-a36e9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4bOz2HaPCYKDM6gALJM7NmPZQpZVfXeE',
    appId: '1:316915061318:ios:508ca53f1799df79acf047',
    messagingSenderId: '316915061318',
    projectId: 'flutter-chat-app-a36e9',
    storageBucket: 'flutter-chat-app-a36e9.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpc2IkMYlCqkWol9ZQSLY8U7o04GjuJgA',
    appId: '1:316915061318:web:af1ce4be8507b959acf047',
    messagingSenderId: '316915061318',
    projectId: 'flutter-chat-app-a36e9',
    authDomain: 'flutter-chat-app-a36e9.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a36e9.firebasestorage.app',
    measurementId: 'G-62M8N9HNBG',
  );

}